title: Devina Lee Sheng Tin
email: dleeshengtin@gmail.com
description: >-
  This site is designed to serve as a portfolio for Devina Lee Sheng Tin.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dtin0906.github.io" # the base hostname & protocol for your site
github_username: dtin0906

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
# Uncomment below if you want to exclude these during build:
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/